blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/Ylim314/CreatorChain/security/advisories/new
    about: Please do not report security issues in public issues.
